version: "3.1"

#volumes:
#  pgdata:
#    driver: local

services:

  tg_bot:
    restart: always
    container_name: tg_bot
    build:
      context: .
#    expose:
#      - 8080
#    ports:
#      - "80:8080"
#    volumes:
#      - ./static:/srv/www/gims-app/static
#      - ./media:/srv/www/gims-app/media
#      - ./sitename.conf:/etc/nginx/conf.d/sitename.conf
    command: "python bot.py"


